apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  namespace: crossplane-system
spec:
  package: "crossplane/provider-aws:v0.30.1"
  controllerConfigRef:
    name: aws-config