# TODO: Create helm for MRs
apiVersion: eks.aws.upbound.io/v1beta2
kind: Cluster
metadata:
  name: crossplane-cluster
  labels:
    app: "crossplane"
spec:
  forProvider:
    region: us-east-1
    roleArnRef:
      name: crossplane-eks-role
    vpcConfig:
      securityGroupIdRefs:
        - name: crossplane-cluster-nodes-sg
      subnetIdSelector:
        matchLabels:
          cluster: crossplane-eks
    version: "1.32"
  writeConnectionSecretToRef:
    name: cluster-conn
    namespace: default
  providerConfigRef:
    name: default