apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: crossplane-eks-cluster-policy
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
    roleNameRef:
      name: crossplane-eks-role
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: crossplane-eks-cluster-policy
    namespace: crossplane-system
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: crossplane-eks-nodes-policy
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
    roleNameRef:
      name: crossplane-eks-role
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: crossplane-eks-nodes-policy
    namespace: crossplane-system