apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: crossplane-eks-role
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "ec2.amazonaws.com",
                        "eks.amazonaws.com",
                        "eks-fargate-pods.amazonaws.com",
                        "lambda.amazonaws.com",
                        "s3.amazonaws.com",
                        "rds.amazonaws.com",
                        "dax.amazonaws.com"
                    ]
                },
                "Action": [
                    "sts:AssumeRole"
                ]
            }
        ]
      }
    tags:
      Name: crossplane-eks-role
      app: crossplane
  providerConfigRef:
    name: default