# https://marketplace.upbound.io/providers/upbound/provider-aws-ec2/v1.22.0
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: crossplane-eks-vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: us-east-1
    tags:
      Name: crossplane-eks-vpc
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: crossplane-eks-vpc
    namespace: crossplane-system
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: crossplane-private-subnet-1
  labels:
    type: private
    cluster: crossplane-eks
spec:
  forProvider:
    vpcIdRef:
      name: crossplane-eks-vpc
    cidrBlock: 10.0.0.0/20
    region: us-east-1
    availabilityZone: us-east-1a
    tags:
      Name: crossplane-private-subnet-1
      kubernetes.io/cluster/crossplane-eks-cluster: shared
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: crossplane-private-subnet-2
  labels:
    type: private
    cluster: crossplane-eks
spec:
  forProvider:
    vpcIdRef:
      name: crossplane-eks-vpc
    cidrBlock: 10.0.16.0/20
    region: us-east-1
    availabilityZone: us-east-1b
    tags:
      Name: crossplane-private-subnet-2
      kubernetes.io/cluster/crossplane-eks-cluster: shared
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: crossplane-private-subnet-3
  labels:
    type: private
    cluster: crossplane-eks
spec:
  forProvider:
    vpcIdRef:
      name: crossplane-eks-vpc
    cidrBlock: 10.0.32.0/20
    region: us-east-1
    availabilityZone: us-east-1c
    tags:
      Name: crossplane-private-subnet-3
      kubernetes.io/cluster/crossplane-eks-cluster: shared
  providerConfigRef:
    name: default